<a href="https://colab.research.google.com/github/aronsalinas96/tensorflow_basics/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we're going to cover some of the most fundamental concepts of tensors using TensorFlow

More specifically, we're going to cover:

* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & NumPy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPUs with TensorFlow (or TPUs)


In [ ]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.7.0


In [ ]:
# Create tensors with tf.constan()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check the dimension of our vector
vector.ndim

1

In [ ]:
# Create a matrix
matrix = tf.constant([[10, 7],[7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# Create a tensor 3d
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                      [10, 11, 12]],
                    [[13, 14, 15],
                     [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

What we've created so far:

* Scalar: a single number.
* Vector: a number with direction (e.g. wind speed and direction).
* Matrix: a 2-dimensional array.
* Tensor: a n-dimensional array.

## Creating tensors with tf.Variable

In [ ]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
changeable_tensor[0].assign(9)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([9, 7], dtype=int32)>

In [ ]:
#Unchangeable tensor are constant, they can't be modified
unchangeable_tensor[0].assign(9)
unchangeable_tensor

AttributeError: ignored

## Creating random tensors

In [ ]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_1

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

random_1, random_2, random_1 == random_2 #They are not really random because of the seed

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

## Shuffle the order of elements in a tensor

In [ ]:
not_shuffled = tf.constant([[10, 7],
                            [2, 5],
                            [3, 4]])

tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

## Other ways to make tensors


In [ ]:
tf.ones([3, 3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros(shape=(3, 3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

## Turn NumPy arrays into tensors

The main difference between Numpy arrays and TensorFlow tensors is that tensors can be run on a GPU/TPU much faster for numerical computing

In [ ]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A
#X = tf.constant(some_matrix) # capital for matrix or tensor
#y = tf.constant(vector) # non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A, shape=(2, 3, 4))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

## Getting information from your tensors (tensor attributes)

* Shape
* Rank
* Axis or dimension
* Size

In [ ]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor


<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

## Indexing tensors

Tensors can be indexed just like Python lists.

In [ ]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[:1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [ ]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[1, 2], 
                             [3, 4]])
rank_2_tensor.shape

TensorShape([2, 2])

In [ ]:
# Get the last item of each row of rank 2 tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

In [ ]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor, axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[1, 2]],

       [[3, 4]]], dtype=int32)>

## Manipulating tensors (tensor operations)

**Basic operations**

`+`,`-`,`*`,`/`

In [ ]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[1, 2],[3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [ ]:
# Multiplication
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [ ]:
# Substraction
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-9, -8],
       [-7, -6]], dtype=int32)>

In [ ]:
# Faster on GPU
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

**Matrix multiplication**

In machine learning, matrix multiplication is one of the most commons operations.

There are two rules our tensors or matrices need to fulfil if we're going to matrx multiply them:

1. The inner dimensions must match.
2. The resulting matrix has the shape of the inner dimensions.

In [ ]:
# Matrix multiplication in tensorflow
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [ ]:
tensor * tensor 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

In [ ]:
tensor @ tensor == tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True]])>

In [ ]:
X = tf.constant([
                     [1, 2],
                     [3, 4],
                     [5, 6],
                     [7, 8],])

Y = tf.constant([
                 [2, 2],
                 [2, 2], 
                 [2, 2]])

X, Y

(<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[2, 2],
        [2, 2],
        [2, 2]], dtype=int32)>)

In [ ]:
tf.multiply(X, Y) # Inner dimensions of X(2) and Y(3) does not match

InvalidArgumentError: ignored

In [ ]:
# Let's change the shape of Y
Y, tf.reshape(Y, shape=(2, 3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[2, 2],
        [2, 2],
        [2, 2]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[2, 2, 2],
        [2, 2, 2]], dtype=int32)>)

In [ ]:
X @ tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 6,  6,  6],
       [14, 14, 14],
       [22, 22, 22],
       [30, 30, 30]], dtype=int32)>

In [ ]:
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 6,  6,  6],
       [14, 14, 14],
       [22, 22, 22],
       [30, 30, 30]], dtype=int32)>

In [ ]:
X, tf.transpose(X), tf.reshape(X, shape=(2, 4)) # transpose 'spins' one axis, reshape 'fit' elements on reshaped axis

(<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]], dtype=int32)>, <tf.Tensor: shape=(2, 4), dtype=int32, numpy=
 array([[1, 3, 5, 7],
        [2, 4, 6, 8]], dtype=int32)>, <tf.Tensor: shape=(2, 4), dtype=int32, numpy=
 array([[1, 2, 3, 4],
        [5, 6, 7, 8]], dtype=int32)>)

## The dot product

Matrix multiplication is also refered as the dot product.

You can perform matrix multiplication using:
* tf.matmul()
* tf.tensordot()

In [ ]:
X, Y = tf.constant([[1, 2],[3, 4], [5, 6]]), tf.constant([[2, 2], [1, 1], [3, 3]])


In [ ]:
tf.tensordot(tf.transpose(X), Y, axes=0), tf.tensordot(tf.transpose(X), Y, axes=1), tf.tensordot(tf.transpose(X), Y, axes=2)

(<tf.Tensor: shape=(2, 3, 3, 2), dtype=int32, numpy=
 array([[[[ 2,  2],
          [ 1,  1],
          [ 3,  3]],
 
         [[ 6,  6],
          [ 3,  3],
          [ 9,  9]],
 
         [[10, 10],
          [ 5,  5],
          [15, 15]]],
 
 
        [[[ 4,  4],
          [ 2,  2],
          [ 6,  6]],
 
         [[ 8,  8],
          [ 4,  4],
          [12, 12]],
 
         [[12, 12],
          [ 6,  6],
          [18, 18]]]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[20, 20],
        [26, 26]], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=45>)

In [ ]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 6,  3,  9],
       [14,  7, 21],
       [22, 11, 33]], dtype=int32)>

In [ ]:
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 4,  8,  7],
       [10, 18, 15],
       [16, 28, 23]], dtype=int32)>

Transpose rather than reshaping tensors is the most common, since it satisfy the matrix maltiplication rules and expected output. 

## Changing the datatype of a tensor

In [ ]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [ ]:
C = tf.constant([1, 2])
C.dtype

tf.int32

In [ ]:
# Change from float32 to float16 (reduced precision)
B = tf.cast(B, dtype=tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

## Aggregating tensors

Aggregating tensors = condensing them from multiple values down to a smaller amount of values.

In [ ]:
D = tf.constant([-1, -2])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-1, -2], dtype=int32)>

In [ ]:
# Get the absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

We will:

* Get the minimum.
* Get the maximum.
* Get the mean of a tensor
* Get the sum of a tensor

In [ ]:
E = tf.constant(np.random.randint(0, 100, size = 25))
E

<tf.Tensor: shape=(25,), dtype=int64, numpy=
array([ 8, 87, 50, 82, 48, 66,  6, 67,  5, 72, 31, 26,  1, 46, 29, 12,  7,
        7, 72, 64, 78,  8, 28, 10,  3])>

In [ ]:
tf.reduce_min(E), tf.reduce_max(E), tf.reduce_mean(E), tf.reduce_sum(E)

(<tf.Tensor: shape=(), dtype=int64, numpy=1>,
 <tf.Tensor: shape=(), dtype=int64, numpy=87>,
 <tf.Tensor: shape=(), dtype=int64, numpy=36>,
 <tf.Tensor: shape=(), dtype=int64, numpy=913>)

In [ ]:
import tensorflow_probability as tfp
# Variance, standar deviation
tfp.stats.variance(E), tf.math.reduce_std(tf.cast(E, tf.float32))

(<tf.Tensor: shape=(), dtype=int64, numpy=842>,
 <tf.Tensor: shape=(), dtype=float32, numpy=29.028427>)

## Find the positional minimum and maximum

In [ ]:
F = tf.random.uniform(shape=[10])
F

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.1801033 , 0.983709  , 0.3244636 , 0.81681025, 0.03150856,
       0.56803536, 0.04562056, 0.5180869 , 0.9376172 , 0.51971245],
      dtype=float32)>

In [ ]:
tf.argmax(F), F[tf.argmax(F)], F[1].numpy() # index, tensor with value, value

(<tf.Tensor: shape=(), dtype=int64, numpy=1>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.983709>,
 0.983709)

In [ ]:
tf.argmin(F), F[tf.argmin(F)], F[4].numpy()

(<tf.Tensor: shape=(), dtype=int64, numpy=4>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.031508565>,
 0.031508565)

### Squeezing a tensor (removing all single dimensions)

In [ ]:
G = tf.constant(tf.random.uniform(shape=[10]), shape=(1,1,1,1,10))
G

<tf.Tensor: shape=(1, 1, 1, 1, 10), dtype=float32, numpy=
array([[[[[0.1372838 , 0.6297945 , 0.36353624, 0.7658497 , 0.6202872 ,
           0.64115524, 0.16284788, 0.69161737, 0.25712717, 0.28814614]]]]],
      dtype=float32)>

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.1372838 , 0.6297945 , 0.36353624, 0.7658497 , 0.6202872 ,
       0.64115524, 0.16284788, 0.69161737, 0.25712717, 0.28814614],
      dtype=float32)>

# One hot encoding tensors

In [ ]:
tf.one_hot([0, 1, 2], depth=3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [ ]:
tf.one_hot([0, 1, 2], depth=3, on_value="YES!!!", off_value="NO")

<tf.Tensor: shape=(3, 3), dtype=string, numpy=
array([[b'YES!!!', b'NO', b'NO'],
       [b'NO', b'YES!!!', b'NO'],
       [b'NO', b'NO', b'YES!!!']], dtype=object)>

## Squaring, log, square root

In [ ]:
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [ ]:
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

## Tensors and Numpy

TensorFlow interacts beautifully with NumPy arrays.

In [ ]:
# Create a tensor from a Numpy array
J = tf.constant(np.array([1., 2., 3., 4.]))
J

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([1., 2., 3., 4.])>

In [ ]:
np.array(J), type(np.array(J))

(array([1., 2., 3., 4.]), numpy.ndarray)

In [ ]:
numpy_J = tf.constant(np.array([1., 2., 3., 4.]))
tensor_J = tf.constant([1., 2., 3., 4.])

numpy_J.dtype, tensor_J.dtype # Float64 is default type for numpy vs float32 in tensor

(tf.float64, tf.float32)

#Finding access to GPU

In [ ]:
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Wed Feb  9 21:47:46 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   34C    P8    28W / 149W |      3MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

**Note:** If you have access to a CUDA-enabled GPU, TensorFlow will automatically use it whenever possible